//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP323_Anisimov_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusyPlaces
    {
        public int IDPlace { get; set; }
        public int IDSession { get; set; }
        public int ID { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
