//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP323_Anisimov_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieGenres
    {
        public int MovieID { get; set; }
        public int GenreID { get; set; }
        public string Description { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
